# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_missknn_impute_numeric_column <- function(numeric_scaled, numeric_raw, categorical_codes, col_types, numeric_pos, categorical_pos, donor_rows, receiver_rows, target_col, weights, k, aggregation, estimator, stochastic, epsilon, ridge, reg_neighbors) {
    .Call(`_missknn_cpp_missknn_impute_numeric_column`, numeric_scaled, numeric_raw, categorical_codes, col_types, numeric_pos, categorical_pos, donor_rows, receiver_rows, target_col, weights, k, aggregation, estimator, stochastic, epsilon, ridge, reg_neighbors)
}

cpp_missknn_impute_categorical_column <- function(numeric_scaled, categorical_codes, col_types, numeric_pos, categorical_pos, donor_rows, receiver_rows, target_col, weights, k, aggregation, stochastic, epsilon) {
    .Call(`_missknn_cpp_missknn_impute_categorical_column`, numeric_scaled, categorical_codes, col_types, numeric_pos, categorical_pos, donor_rows, receiver_rows, target_col, weights, k, aggregation, stochastic, epsilon)
}

cpp_missknn_tune_numeric <- function(numeric_scaled, numeric_raw, categorical_codes, col_types, numeric_pos, categorical_pos, weights, epsilon, ridge, target_cols, train_list, hold_list, k_grid_list) {
    .Call(`_missknn_cpp_missknn_tune_numeric`, numeric_scaled, numeric_raw, categorical_codes, col_types, numeric_pos, categorical_pos, weights, epsilon, ridge, target_cols, train_list, hold_list, k_grid_list)
}

cpp_missknn_tune_categorical <- function(numeric_scaled, categorical_codes, col_types, numeric_pos, categorical_pos, weights, epsilon, target_cols, train_list, hold_list, k_grid_list) {
    .Call(`_missknn_cpp_missknn_tune_categorical`, numeric_scaled, categorical_codes, col_types, numeric_pos, categorical_pos, weights, epsilon, target_cols, train_list, hold_list, k_grid_list)
}

